=== DKAndreasen/KI_klargoer_tekster/FSIII_helbredstilstande.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/DKAndreasen/KI_klargoer_tekster/main/FSIII_helbredstilstande.schema.json",
  "title": "Validation schema for Fællessprog III helbredstilstande, version 0.1",
  "description": "NB: this schema is for demonstration purposes and its content have not be verified nor approved by anyone with relation to KOMBIT or Fællessprog III. This schema documents the fields for Fællessprog III helbredstilstande",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "kategori": {
        "description": "Kategori af helbredstilstande",
        "enum": [
          "Funktionsniveau",
          "Bevægeapparat",
          "Ernæring",
          "Hud og slimhinder",
          "Kommunikation",
          "Psykosociale forhold",
          "Respiration og cirkulation",
          "Seksualitet",
          "Smerter og sanseindtryk",
          "Søvn og hvile",
          "Viden og udvikling",
          "Udskillelse af affaldsstoffer"
        ]
      },
      "titel": {
        "description": "Betegnelse for helbredstilstanden",
        "type": "string"
      },
      "beskrivelse": {
        "description": "Beskrivelse af helbredstilstanden",
        "type": "string"
      },
      "eksempel": {
        "description": "Eksempler på hvordan helbredstilstanden kan tage sig ud i praksis",
        "type": "string"
      },
      "medsendes_indlaeggelsesrapporten": {
        "description": "Tilstandsområdet sendes med i indlæggelsesrapporten fra kommunen til sygehuset",
        "type": "boolean"
      }
    },
    "additionalProperties": false,
    "required": [
      "kategori",
      "titel",
      "beskrivelse",
      "eksempel",
      "medsendes_indlaeggelsesrapporten"
    ]
  }
}

=== DKAndreasen/KI_klargoer_tekster/FSIII_helbredstilstande.json
[
  {
    "kategori": "Funktionsniveau",
    "titel": "Problemer med personlig pleje",
    "beskrivelse": "Vælges når borger har problemer med at varetage personlig pleje som følge af sygdom, skade eller handicap, og hvor kompleksiteten eller en kritisk situation kræver et særligt kompetenceniveau hos personalet, eller ved brug for støtte til kropspleje, af- og påklædning og/eller toiletbesøg",
    "eksempel": "Fx besvær med at varetage den daglige hygiejne, herunder kropspleje og toiletbesøg, som følge af andet helbredsproblem",
    "medsendes_indlaeggelsesrapporten": false
  }, {
    "kategori": "Funktionsniveau",
    "titel": "Problemer med daglige aktiviteter",
    "beskrivelse": "Vælges når borgeren har problemer med at aretage daglige aktiviteter, og hvor kompleksiteten eller en kritisk situation kræver et særligt kompetenceniveau hos personalet.\n Fx behov for hjælp til koordinering og planlægning af daglige aktiviteter ved tab af fysisk-, mental- og social funktionsevne, eller ved brug for anden støtte til planlægning og koordinering af dagligdagen.",
    "eksempel": "Fx manglende overblik og initiativ.",
    "medsendes_indlaeggelsesrapporten": false 
  }, {
    "kategori": "Bevægeapparat",
    "titel": "Problemer med mobilitet og bevægelse",
    "beskrivelse": "Vælges når borgeren har problemer med bevægelses-forstyrrelser og problemer med at bevæge sig, forflytte sig, ændre kropsstilling eller ved inaktivitet som følge af sygdom, skade eller behandling, fx bivirkning af medicin, eller ved brug for anden støtte til at ændre kropsstilling, forflytning og/eller at bevæge sig omkring. Fx borgere med Parkinsons sygdom og essentiel tremor.",
    "eksempel": "Fx tremor, bevægelseshæmning, ufrivillige bevægelser, muskelstivhed, lammelser, spasticitet, ledstivhed, styringsbesvær eller nedsat muskelstyrke. Immobilitet, kontrakturer, svimmelhed, faldtendens, balanceproblemer.",
    "medsendes_indlaeggelsesrapporten": true  
  }, {
    "kategori": "Ernæring",
    "titel": "Problemer med væskeindtag",
    "beskrivelse": "Vælges når borgeren har problemer med at indtage en korrekt mængde væske som følge af sygdom eller behandling, fx bivirkning af medicin, hvor der er risiko for dehydrering eller overhydrering, eller ved brug for anden støtte til væskeindtag.",
    "eksempel": "Fx synkeproblemer, fejlsynkning, nedsat eller øget tørst, kvalme og opkast, træthed, forvirring og konfusion, svimmelhed, nedsat hudturgor.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Ernæring",
    "titel": "Problemer med fødeindtag",
    "beskrivelse": "Vælges når borgeren har problemer med at indtage eller optage ernæring og vitaminer/mineraler eller ved ernæringsbetingede stofskifteproblematikker som følge af sygdom eller behandling, fx bivirkning af medicin. \nFx borgere med dysfagi eller korttarmssyndrom, eller andre der modtager ernæring enten parenteral eller via sonde, eller ved brug for anden støtte til fødeindtag. \nTilstanden vælges også ved borgere med diabetes.",
    "eksempel": "Fx tygge-/synkeproblemer, fejlsynkning, kvalme eller opkast, problemer med at optage eller indtage ernæring, vitaminer og mineraler. \nHvis borgeren har diabetes, beskrives de symptomer borgeren har ved for hypoeller hyperglykæmi. \nHypoglykæmi – fx træthed, øget svedtendens, sitren/rysten, bleghed, svimmelhed, koncentrationsbesvær, ændret adfærd. \nHyperglykæmi – fx øget tørst og vandladning, mundtørhed, hudkløe, kvalme, træthed, vægttab.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Ernæring",
    "titel": "Uhensigtsmæssig vægtændring",
    "beskrivelse": "Vælges når borgeren har problemer med pludselig vægtændring som følge af sygdom eller behandling, fx bivirkning af medicin, eller brug for anden støtte til at håndtere uplanlagt vægtændring.",
    "eksempel": "Pludseligt vægttab eller vægtøgning.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Ernæring",
    "titel": "Problemer med overvægt",
    "beskrivelse": "Vælges når borgeren har problemer med overvægt som følge af sygdom eller behandling, fx bivirkning af medicin, eller brug for anden støtte til at håndtere overvægt.",
    "eksempel": "Fx højt BMI, vægtstigning, øget appetit, overspisning.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Ernæring",
    "titel": "Problemer med undervægt",
    "beskrivelse": "Vælges når borgeren har problemer med vægttab og undervægt som følge af sygdom eller behandling, fx bivirkning af medicin, eller brug for anden støtte til at håndtere undervægt.",
    "eksempel": "Fx lavt BMI, vægttab, småtspisende, manglende appetit, kvalme og/eller opkast, tygge-/synkeproblemer som følge af dårlig tandstatus, træthed, mangel på energi, koncentrationsbesvær.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med kirurgisk sår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som følge af et kirurgisk indgreb efter en operation, eller brug for anden støtte til behandling af kirurgisk sår.",
    "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med diabetisk sår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som en senkomplikation til diabetes, eller brug for anden støtte til behandling af diabetisk sår.",
    "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med cancersår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som følge af cancer og metastaser, eller brug for anden støtte til behandling af cancersår.",
    "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med tryksår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som følge af tryk og/eller shear, eller brug for anden støtte til behandling af tryksår.",
    "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med arterielt sår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som følge af nedsat arteriel blodtilførsel, eller brug for anden støtte til behandling af arterielt sår.",
    "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med venøst sår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som følge af venøs insufficiens, typisk manglende funktion af veneklapperne, eller brug for anden støtte til behandling af venøst sår.",
    "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med blandingssår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som følge af arteriel og venøs insufficiens, typisk en forværring af et venøst sår, eller brug for anden støtte til behandling af blandingssår.",
   "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Problemer med traumesår",
    "beskrivelse": "Vælges når borgeren har problemer med sår, der er opstået som følge af traumer på hårdt væv og/eller bløddele. \nFx efter fald eller anden ulykke, snitsår, hudafskrabninger, brandsår, ætsninger eller forfrysninger, eller brug for anden støtte til behandling af traumesår.",
    "eksempel": "Beskriv sårets placering, størrelse, udseende samt evt. gener såret medfører for borgeren. \nFx sårbund, sårkant, sekretion og omkringliggende hud.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Hud og slimhinder",
    "titel": "Andre problemer med hud og slimhinder",
    "beskrivelse": "Vælges når borgeren har problemer med hud og slimhinder som ikke er sår. \nFx borgere der har svampeinfektion, fnat eller MRSA, eller brug for anden støtte til behandling af hud- og slimhindeproblemer som ikke er sår.",
    "eksempel": "Beskriv problemets placering, størrelse, udseende samt de evt. gener det medfører hos borgeren. \nFx kløe, kradsemærker, udslet, skællende hud, rødme, eksem, ændringer i hudens farve, hvide belægninger, hudløshed, blå mærker, ødemer.",
    "medsendes_indlaeggelsesrapporten": true
  }, {
    "kategori": "Kommunikation",
    "titel": "Problemer med kommunikation",
    "beskrivelse": "Vælges når borgeren har problemer med at tale, forstå, skrive, stave og læse som følge af sygdom, skade eller behandling, fx bivirkning af medicin. Fx borgere med en svær hjerneskade og/eller nedsat bevidsthedsniveau, eller brug for anden støtte til kommunikation.",
